#!/bin/sh

script=`basename $0`

case $# in

    0)
        vi
        exit 0
        ;;

    1)

        # 읽기 또는 쓰기 권한 검사
        if [ ! -r "$1" -o ! -w "$1" ]; then
            echo "$script: check permission on $1" 1>&2
            exit 1
        fi

        # 현재 디렉토리 쓰기 권한 검사
        if [ ! -w "." ]; then
            echo "$script: backup cannot be created in the working directory" 1>&2
            exit 2
        fi

        editfile=$1

        # 일반 파일인지 검사
        if [ ! -f "$1" ]; then
            echo "$1 is not regular file."
            exit 1
        fi
        ;;

    *)
        echo "Usage: $script filename"
        exit 1
        ;;
esac

tempfile=/tmp/$$.$script

cp "$editfile" "$tempfile"

if vi "$editfile"
then
    mv "$tempfile" "`basename $editfile`.bak"
    echo "$script: backup file created"

else
    mv "$tempfile" editerr
    echo "$script: edit error-copy of original file is in editerr" 1>&2
fi
